version: '3.5'

services:
  composer_install:
    container_name: composer_install_bumo
    image: composer
    volumes:
      - ./:/app
    command: composer update
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  phpwebserver:
    container_name: phpwebserver
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
      - "12345:12345"
      - "2022:2022"
      - "2020:2020"
    volumes:
      - ./:/var/www
    logging:
      driver: "json-file"
      options:
        max-size: "10m"